#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the getMinimumCost function below.
def getMinimumCost(k, c, n):
    if n<len(c):
        n = len(c)

    totalCount, perPerson, curRound, totalAmount = 0, 0, 0, 0
    pFlower = len(c) - 1
    while totalCount < n:
        totalAmount += c[pFlower]*(perPerson+1)
    
        curRound += 1
        if curRound == k:
            curRound = 0
            perPerson += 1
        totalCount += 1
        pFlower -= 1

    return(totalAmount)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    minimumCost = getMinimumCost(k, c, n)

    fptr.write(str(minimumCost) + '\n')

    fptr.close()
