#!/bin/python3

import math
import os
import random
import re
import sys


#

def maxMin(k, arr,n):
    
    arr.sort()
    # N=20,k=5 , min[arr[4] - arr[0],arr[5]-arr[1].....arr[19]-arr[15] ]
    return min([abs(arr[i+k-1]-arr[i]) for i in range(n-k+1)])
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    k = int(input().strip())

    arr = []

    for _ in range(n):
        arr_item = int(input().strip())
        arr.append(arr_item)

    result = maxMin(k, arr,n)

    fptr.write(str(result) + '\n')

    fptr.close()
